# Lab Task 01

Reshape a 1D NumPy array into a 2D array with dimensions (3, 4).

Concatenate two NumPy arrays horizontally and vertically.

In [7]:
import numpy as np

arr_1d = np.arange(12)  # Example 1D array
arr_2d = arr_1d.reshape(3, 4)

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr_h = np.concatenate((arr1, arr2))
arr_v = np.concatenate((arr1.reshape(-1, 1), arr2.reshape(-1, 1)), axis=1)

print(arr_2d)
print(arr_h)
print(arr_v)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[1 2 3 4 5 6]
[[1 4]
 [2 5]
 [3 6]]


# Lab Task 02


## Email Classification
Develope a tool which will classify an email.

### Tasks:
* Create a function classify_emails that takes a list of emails as an argument.
* Inside the function, categorize emails into "Important," "Promotions," and "Spam" based on keywords and content analysis.
* Loop through the emails and identify keywords to determine their category.
* If an email contains keywords indicating importance, assign it as "Important."
* If an email contains keywords related to promotions or deals, assign it as "Promotions."
* If an email is suspected to be spam based on certain keywords or patterns, assign it as "Spam."
* Return three lists of emails for each category.
* Print the lists.

In [11]:
emails = [
    "Limited Time Sale: Get 50% OFF Now!",
    "Urgent: Update Your Account Information",
    "You've Won a Free Trip! Claim Now",
    "Important: Meeting Rescheduled to 10am",
    "Exclusive Deal: Members Only Discount"
]

important_emails = []
promotions_emails = []
spam_emails = []

important_keywords = ['urgent', 'immediate', 'attention', 'important']
promotions_keywords = ['sale', 'deal', 'discount', 'exclusive']
spam_keywords = ['win', 'prize', 'offer', 'free']

def classify_email(email, important_keywords, promotions_keywords, spam_keywords):
    email_lower = email.lower()

    for keyword in important_keywords:
        if keyword in email_lower:
            return 'important'

    for keyword in promotions_keywords:
        if keyword in email_lower:
            return 'promotions'

    for keyword in spam_keywords:
        if keyword in email_lower:
            return 'spam'

    return 'spam'

for email in emails:
    classification = classify_email(email, important_keywords, promotions_keywords, spam_keywords)
    if classification == 'important':
        important_emails.append(email)
    elif classification == 'promotions':
        promotions_emails.append(email)
    elif classification == 'spam':
        spam_emails.append(email)

print("Important Emails:", important_emails)
print("Promotions Emails:", promotions_emails)
print("Spam Emails:", spam_emails)


Important Emails: ['Urgent: Update Your Account Information', 'Important: Meeting Rescheduled to 10am']
Promotions Emails: ['Limited Time Sale: Get 50% OFF Now!', 'Exclusive Deal: Members Only Discount']
Spam Emails: ["You've Won a Free Trip! Claim Now"]


# Lab Task 03

## English-Spanish Dictionary
You are creating a basic English-Spanish dictionary that allows users to look up English words and find their Spanish translations.


### Tasks
* Create a dictionary where English words are keys and their Spanish translations are values.
* Ask the user to input an English word.
* Check if the word exists in the dictionary.
* If the word exists, print its Spanish translation.
* If the word does not exist, inform the user that the translation is not available.
* Implement a loop that allows the user to keep looking up words until they choose to exit.


In [13]:
dict_en_es = {"hello": "hola", "hi": "hola"}

def find_translation(d):
    while True:
        word = input("Enter word to translate or exit to quit : ").lower()

        if word == 'exit':
            print("Exiting")
            break

        if word in d:
            print(f"Translation : '{d[word]}'")
        else:
            print("Not found")

find_translation(dict_en_es)



Enter word to translate or exit to quit : hello
Translation : 'hola'
Enter word to translate or exit to quit : hi
Translation : 'hola'
Enter word to translate or exit to quit : exit
Exiting


# Lab Task 04

dataset link : https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv
#Exercise
Use the dataset of Game, we have explored earlier and perform following operations.

* Calculate the total global sales for all games in the dataset.
* Find the game with the highest global sales.
* Determine the average sales for each region (NA_Sales, EU_Sales, JP_Sales, Other_Sales).
* Find the top 5 most popular game genres based on global sales.
* Calculate the total sales for each genre in each region and find the most popular genre in North America (NA_Sales).
* Display last 10 rows.
* Determine the top 3 gaming platforms with the highest global sales.
* Calculate the market share (percentage of global sales) for each genre.
* Calculate the correlation coefficient between NA_Sales and EU_Sales. (.corr function)

Some tree example

In [15]:
import pandas as pd

data = {
    "Name": ["A", "B"],
    "Platform": ["PS3", "PS5"],
    "Genre": ["Adv", "horror"],
    "NA": [3.0, 8.5],
    "EU": [5.0, 2.2, ],
    "JP": [1.5, 2.3,],
    "Other": [2.0, 1.8],
    "Global": [5.5, 2.1]
}
games = pd.DataFrame(data)

# Total global sales
total_global = games['Global'].sum()

# Highest global sales
max_global_game = games.loc[games['Global'].idxmax()]

# Avg sales per region
avg_region = games[['NA', 'EU', 'JP', 'Other']].mean()

# Top 5 genres by gs
top_genres = games.groupby('Genre')['Global'].sum().nlargest(5)

# Total sales per genre in each region and most popular in NA
genre_sales = games.groupby('Genre')[['NA', 'EU', 'JP', 'Other']].sum()
top_genre_na = genre_sales['NA'].idxmax()

# Last rows
last_rows = games.tail()

# Top 3 platforms by gs
top_platforms = games.groupby('Platform')['Global'].sum().nlargest(3)

# Market share
genre_share = games.groupby('Genre')['Global'].sum() / total_global * 100

# Correlation
corr_na_eu = games[['NA', 'EU']].corr()

print(f"Total Global Sales : {total_global}")
print(f"Game with Highest Global Sales : {max_global_game['Name']}")
print(f"Average Sales per Region : {avg_region}")
print(f"Top 5 Genres by Global Sales : {top_genres}")
print(f"Most Popular Genre in NA : {top_genre_na}")
print("Last Rows Displayed :")
print(last_rows)
print(f"Top 3 Platforms by Global Sales : {top_platforms}")
print(f"Market Share : {genre_share}")
print(f"Correlation : {corr_na_eu}")


Total Global Sales : 7.6
Game with Highest Global Sales : A
Average Sales per Region : NA       5.75
EU       3.60
JP       1.90
Other    1.90
dtype: float64
Top 5 Genres by Global Sales : Genre
Adv       5.5
horror    2.1
Name: Global, dtype: float64
Most Popular Genre in NA : horror
Last Rows Displayed :
  Name Platform   Genre   NA   EU   JP  Other  Global
0    A      PS3     Adv  3.0  5.0  1.5    2.0     5.5
1    B      PS5  horror  8.5  2.2  2.3    1.8     2.1
Top 3 Platforms by Global Sales : Platform
PS3    5.5
PS5    2.1
Name: Global, dtype: float64
Market Share : Genre
Adv       72.368421
horror    27.631579
Name: Global, dtype: float64
Correlation :      NA   EU
NA  1.0 -1.0
EU -1.0  1.0


In [ ]:
# import pandas as pd

# # Create a DataFrame to represent a tree
# data = {
#     'node': ['A', 'B', 'C', 'D', 'E', 'F'],
#     'parent': [None, 'A', 'A', 'B', 'B', 'C']
# }
# df = pd.DataFrame(data)

# print(df)


In [ ]:
# pip install networkx


In [ ]:
# import pandas as pd
# import networkx as nx
# import matplotlib.pyplot as plt

# # Create a DataFrame representing edges in a graph
# data = {
#     'from': ['A', 'A', 'B', 'C', 'D'],
#     'to': ['B', 'C', 'D', 'E', 'E']
# }
# edges = pd.DataFrame(data)

# # Create a graph from the edges DataFrame
# G = nx.from_pandas_edgelist(edges, 'from', 'to')

# # Draw the graph
# nx.draw(G, with_labels=True)
# plt.show()

# # Analyze the graph
# print("Nodes:", G.nodes())
# print("Edges:", G.edges())
# print("Degree for each Node:", dict(G.degree()))
